spring:
  application:
    name: rohlik
  datasource:
    url: jdbc:h2:mem:rohlik;mode=PostgreSQL;database_to_lower=true;
    driverClassName: org.h2.Driver
    username: admin
    password: password
  quartz:
    jdbc:
      initialize-schema: always
    job-store-type: jdbc
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
springdoc:
  swagger-ui:
    path: /swagger-ui.html
rohlik:
  order:
    unpaid-cancellation-minutes: 2
logging:
  level:
    cz.rohlik: INFO
